Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-7"
  c.vm.hostname = "vanilla-rhel-7-couchbase-660-enterprise.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/chassenfeldt/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-couchbase-enterprise-srg-baseline-vanilla-rhel-7-couchbase-660-enterprise-a6581a5a-a63b-4ad4-af92-d765ffd5af0b"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
