- hosts: localhost
  tasks:
    - name: Start service couchbase-server, if not started
      service:
        name: couchbase-server
        state: started
    # - name: Setup new cluster
    #   command: "couchbase-cli cluster-init -c localhost --cluster-username admin --cluster-password password --services data,index,query --cluster-ramsize 512 --cluster-index-ramsize 256"

