FROM couchbase:latest

                         RUN [ ! -f "/sbin/initctl" ] || dpkg-divert --local --rename --add /sbin/initctl && ln -sf /bin/true /sbin/initctl
                         ENV DEBIAN_FRONTEND noninteractive
                         ENV container docker
                         RUN apt-get update
                         RUN apt-get install -y sudo openssh-server curl lsb-release

            RUN if ! getent passwd kitchen; then                   useradd -d /home/kitchen -m -s /bin/bash -p '*' kitchen;                 fi
            RUN echo "kitchen ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
            RUN echo "Defaults !requiretty" >> /etc/sudoers
            RUN mkdir -p /home/kitchen/.ssh
            RUN chown -R kitchen /home/kitchen/.ssh
            RUN chmod 0700 /home/kitchen/.ssh
            RUN touch /home/kitchen/.ssh/authorized_keys
            RUN chown kitchen /home/kitchen/.ssh/authorized_keys
            RUN chmod 0600 /home/kitchen/.ssh/authorized_keys
            RUN mkdir -p /run/sshd


RUN echo ssh-rsa\ AAAAB3NzaC1yc2EAAAADAQABAAABAQDhQYSIWNe/gtfsjna9zWyuLYRiWlsQI5fbcPRpd1GZLzUeM3haOGPd2LMqqyjfBBwyNLLKpxI24xKBlz9lILES/n/Sxrre0/B8jAcrqYBLN/DWUCfBK7FedPhapw\+pli0N0wSHQ/tJR\+Eg1wptZtxi395Msf5mKbPbvk7t\+wwpMCewsHB2qPld4tuGL75Cfj4Kb9vhHNXuUAQjikc9gz9FAV65Dg4dRBHk3Phhrm0Dz4H9YB\+plOnlhiIlAkxoRRjBETFSYr5iOitixudHg0QlzCrVEvDtPXvLq9RiUkhAJ8WLUk0cf5pnuXgnPpqgKPK5nTpTgC0qg2G/Z/EJKfiJ\ kitchen_docker_key >> /home/kitchen/.ssh/authorized_keys
