# ---
- name: Start service couchbase-server, if not started
  service:
    name: couchbase-server
    state: started

- name: Check version of Couchbase server
  shell: "opt/couchbase/bin/couchbase-server -v"
  register: cbversion

- name: Enable Compliant Password Policy Settings 6.0.2 and earlier
  shell: "couchbase-cli setting-password-policy -c 127.0.0.1:8091 -u admin -p password --set 
  --min-length 15 --uppercase --lowercase --digit --special-char"
  when: "'6.0.2' in cbversion.stdout or '6.5.0' in cbversion.stdout"

- name: Enable Compliant Password Policy Settings 6.5 and later
  shell: "couchbase-cli setting-password-policy -c 127.0.0.1:8091 -u admin -p password 
  --set --min-length 15 --uppercase 1 --lowercase 1 --digit 1 --special-char 1"
  when: "'6.5.1' in cbversion.stdout or '6.6.0' in cbversion.stdout"

- name: Configure Couchbase to Generate Audit Records for All Invalid Inputs
  shell: "**************************"

- name: Configure Couchbase to to implement a limit on the lifetime of cached authenticator
  shell: "couchbase-cli setting-ldap -c 127.0.0.1:8091 -u admin -p password --cache-value-lifetime 300000"

- name: Configure Couchbase authorization to be Mandatory 
  shell: "couchbase-cli ssl-manage -c 127.0.0.1:8091 -u admin -p password --set-client-auth mandatory"

# Add steps to harden
