# ---
- name: Start service couchbase-server, if not started
  service:
    name: couchbase-server
    state: started

- name: Setup new cluster
  shell: "/opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1 --cluster-username admin --cluster-password password --services data,index,query --cluster-ramsize 512 --cluster-index-ramsize 256"

- name: Create a Bucket
  shell: "/opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --username admin --password password --bucket test-data --bucket-type couchbase --bucket-ramsize 100"

- name: Create Admin User
  shell: "/opt/couchbase/bin/couchbase-cli user-manage -c 127.0.0.1:8091 -u admin -p password --set --rbac-username cbadmin --rbac-password cbpass --rbac-name 'Admin User' --roles admin --auth-domain local"

- name: Create Regular User
  shell: "/opt/couchbase/bin/couchbase-cli user-manage -c 127.0.0.1:8091 -u admin -p password --set --rbac-username cbuser --rbac-password cbpass --rbac-name 'CB User' --roles bucket_admin[test-data] --auth-domain local"

- name: Check version of Couchbase Server
  shell: "/opt/couchbase/bin/couchbase-server -v"
  register: cbversion

- name: Enable Auditing for Enterprise 6.5.0 and earlier
  shell: "/opt/couchbase/bin/couchbase-cli setting-audit -c 127.0.0.1:8091 -u admin -p password --audit-enabled 1 --audit-log-rotate-interval 604800 --audit-log-path /opt/couchbase/var/lib/couchbase/logs"
  when: "'6.0.2' in cbversion.stdout or '6.5.0' in cbversion.stdout"

- name: Enable Auditing for Enterprise 6.5.1 and later
  shell: "/opt/couchbase/bin/couchbase-cli setting-audit -c 127.0.0.1:8091 -u admin -p password --set --audit-enabled 1 --audit-log-rotate-interval 604800 --audit-log-path /opt/couchbase/var/lib/couchbase/logs"
  when: "'6.5.1' in cbversion.stdout or '6.6.0' in cbversion.stdout"

- name: Set Ownership/Permissions on Couchbase Static Config file
  file:
    path: "{{ cb_static_conf }}"
    mode: "600"
    owner: "couchbase"
    group: "couchbase"

- name: Set Ownership/Permissions on all Log Files
  file:
    path: "{{ cb_log_dir }}"
    recurse: yes
    mode: "600"
    owner: "couchbase"
    group: "couchbase"

- name: Set Ownership/Permissions on Log Directory
  file:
    path: "{{ cb_log_dir }}"
    mode: "700"
    owner: "couchbase"
    group: "couchbase"


# Add steps to harden
