Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-7"
  c.vm.hostname = "hardened-rhel-7-couchbase-660-enterprise.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/chassenfeldt/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-couchbase-enterprise-srg-baseline-hardened-rhel-7-couchbase-660-enterprise-bd7559ec-3f1f-4f89-80fb-7180845dc9bb"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
