# encoding: UTF-8

control "V-32391" do
  title "Couchbase must use system clocks to generate time stamps for use in
audit records and application data."
  desc  "Internal system clocks are typically a feature of server hardware and
are maintained and used by the operating system. They are typically
synchronized with an authoritative time server at regular intervals.

    Without an internal system clock used as the reference for the time stored
on each event to provide a trusted common reference for the time, forensic
analysis would be impeded. Determining the correct time a particular event
occurred on a system is critical when conducting forensic analysis and
investigating system events.

    Time stamps generated by the internal system clock and used by Couchbase
shall include both date and time. The time may be expressed in Coordinated
Universal Time (UTC), a modern continuation of Greenwich Mean Time (GMT), or
local time with an offset from UTC.

    If time sources other than the system time are used for audit records, the
timeline of events can get skewed. This makes forensic analysis of the logs
much less reliable.
  "
  desc  "check", "
  Once enabled on the cluster, Couchbase auditing provides the following
  fields by default:
    - \"id\" - ID of Event
    - \"name\" - Name of Event (can indicate success/failure)
    - \"description\" - Event Description (can indicate success/failure)
    - \"filtering_permitted\" - Whether the event is filterable
    - \"mandatory_fields\" - Includes \"timestamp\" (UTC time and ISO 8601
      format) and \"user\" fields

  As the Full Admin, create a user account by executing the following command:
    $couchbase-cli user-manage -c <host>:<port> -u <Full Admin> \
    -p <Password> --set --rbac-username jdoe --rbac-password cbpass \
    --rbac-name \"John Doe\" --roles replication_admin \
    --auth-domain local
      
  Verify that the event logged contains the required fields:
    $ cat <Couchbase Home>/var/lib/couchbase/logs/audit.log 
      
  If the log does not contain the \"timestamp\" field,
  this is a finding.
  "
  desc  "fix", "
  Enable session auditing on the Couchbase cluster to enable the use of
  system clocks to generate time stamps for audit records.
  
  Couchbase Server 6.5.0 and earlier -
  As the Full Admin, execute the following command to enable auditing:
    $ couchbase-cli setting-audit --cluster <host>:<port> --u <Full Admin>
  --password <Password> --audit-enabled 1 --audit-log-rotate-interval 604800
  --audit-log-path /opt/couchbase/var/lib/couchbase/logs

  Couchbase Server Version 6.51 and later -
  As the Full Admin, execute the following command to enable auditing:
    $ couchbase-cli setting-audit --cluster <host>:<port> --u <Full Admin>
    --password <Password> --set  --audit-enabled 1 --audit-log-rotate-interval
    604800 --audit-log-path /opt/couchbase/var/lib/couchbase/logs
  "
  impact 0.5
  tag "severity": "medium"
  tag "gtitle": "SRG-APP-000116-DB-000057"
  tag "gid": "V-32391"
  tag "rid": "SV-42728r3_rule"
  tag "stig_id": "SRG-APP-000116-DB-000057"
  tag "fix_id": "F-36306r2_fix"
  tag "cci": ["CCI-000159"]
  tag "nist": ["AU-8 a", "Rev_4"]

  describe "Create the jdoe user. The" do 
    subject { command("#{input('cb_bin_dir')}/couchbase-cli user-manage \
    -c #{input('cb_cluster_host')}:#{input('cb_cluster_port')} \
    -u #{input('cb_full_admin')} -p #{input('cb_full_admin_password')} \
    --set --rbac-username jdoe --rbac-password cbpass \
    --rbac-name 'John Doe' --roles replication_admin --auth-domain local") }
    its('exit_status') { should eq 0 }
  end

  describe "The logged event should contain required fields. The" do
    subject { command("grep 'jdoe' #{input('cb_audit_log')} | tail -1") }
    its('stdout') { should match /"timestamp"/}
  end

  describe "Delete the jdoe user. The" do 
    subject { command("#{input('cb_bin_dir')}/couchbase-cli user-manage \
    -c #{input('cb_cluster_host')}:#{input('cb_cluster_port')} \
    -u #{input('cb_full_admin')} -p #{input('cb_full_admin_password')} \
    --delete --rbac-username jdoe --auth-domain local") }
    its('exit_status') { should eq 0 }
  end
end
