# encoding: UTF-8

control "V-32523" do
  title "Couchbase must invalidate session identifiers upon user logout or
other session termination."
  desc  "Captured sessions can be reused in \"replay\" attacks. This
requirement limits the ability of adversaries to capture and continue to employ
previously valid session IDs.

    This requirement focuses on communications protection for Couchbase session
rather than for the network packet. The intent of this control is to establish
grounds for confidence at each end of a communications session in the ongoing
identity of the other party and in the validity of the information being
transmitted.

    Session IDs are tokens generated by Couchbases to uniquely identify a
user's (or process's) session. Couchbases will make access decisions and
execute logic based on the session ID.

    Unique session IDs help to reduce predictability of said identifiers.
Unique session IDs address man-in-the-middle attacks, including session
hijacking or insertion of false information into a session. If the attacker is
unable to identify or guess the session information related to pending
application traffic, they will have more difficulty in hijacking the session or
otherwise manipulating valid sessions.

    When a user logs out, or when any other session termination event occurs,
Couchbase must terminate the user session(s) to minimize the potential for
sessions to be hijacked.
  "
  desc  "rationale", ""
  desc  "check", "
    Review Couchbase settings and vendor documentation to verify user sessions
are terminated, and session identifiers invalidated, upon user logout. If they
are not, this is a finding.
    Review system documentation and organization policy to identify other
events that should result in session terminations.
    If other session termination events are defined, review Couchbase settings
to verify occurrences of these events would cause session termination,
invalidating the session identifiers.
    As the Full Admin, get the current security settings with the following
command:
    $ curl -v -X GET -u <Full Admin>:<Password>
http://<host>:<port>/settings/security
    Review the output of the command. If uiSessionTimeout does not have a
value, this is a finding.
  "
  desc  "fix", "
    Configure Couchbase settings to terminate sessions, invalidating their
session identifiers, upon the occurrence of any organization- or policy-defined
session termination event.
    As the Full Admin, configure session timeout:
    $ curl -X POST -u  <Full Admin>:<Password>\\
http://<host>:<port>/settings/security \\ -d \"uiSessionTimeout=600\"
  "
  impact 0.5
  tag "severity": "medium"
  tag "gtitle": "SRG-APP-000220-DB-000149"
  tag "gid": "V-32523"
  tag "rid": "SV-42860r2_rule"
  tag "stig_id": "SRG-APP-000220-DB-000149"
  tag "fix_id": "F-36438r2_fix"
  tag "cci": ["CCI-001185"]
  tag "nist": ["SC-23 (1)", "Rev_4"]
end
