# encoding: UTF-8

control 'V-58051' do
  title "The DBMS must provide centralized configuration of the content to be
captured in audit records generated by all components of the DBMS."
  desc  "If the configuration of the DBMS's auditing is spread across multiple
locations in the database management software, or across multiple commands,
only loosely related, it is harder to use and takes longer to reconfigure in
response to events.

    The DBMS must provide a unified tool for audit configuration.
  "
  desc  'rationale', ''
  desc  'check', "
    Review DBMS vendor documentation.

    If the DBMS does not provide a unified tool for audit configuration, this
is a finding.
  "
  desc  'fix', "Deploy a DBMS that provides a unified tool for audit
configuration."
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000356-DB-000315'
  tag gid: 'V-58051'
  tag rid: 'SV-72481r1_rule'
  tag stig_id: 'SRG-APP-000356-DB-000315'
  tag fix_id: 'F-63259r1_fix'
  tag cci: ['CCI-001844']
  tag nist: ['AU-3 (2)']
end

