# encoding: UTF-8

control 'V-58063' do
  title "The DBMS must record time stamps, in audit records and application
data, that can be mapped to Coordinated Universal Time (UTC, formerly GMT)."
  desc  "If time stamps are not consistently applied and there is no common
time reference, it is difficult to perform forensic analysis.

    Time stamps generated by the DBMS must include date and time. Time is
commonly expressed in Coordinated Universal Time (UTC), a modern continuation
of Greenwich Mean Time (GMT), or local time with an offset from UTC.

    Some DBMS products offer a data type called TIMESTAMP that is not a
representation of date and time. Rather, it is a database state counter and
does not correspond to calendar and clock time. This requirement does not refer
to that meaning of TIMESTAMP.
  "
  desc  'rationale', ''
  desc  'check', "
    Verify that the DBMS generates time stamps, in audit records and
application data, that maps to UTC.

    If it does not, this is a finding.
  "
  desc  'fix', "Ensure the DBMS generates time stamps, in audit records and
application data, that maps to UTC."
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000374-DB-000322'
  tag gid: 'V-58063'
  tag rid: 'SV-72493r1_rule'
  tag stig_id: 'SRG-APP-000374-DB-000322'
  tag fix_id: 'F-63271r1_fix'
  tag cci: ['CCI-001890']
  tag nist: ['AU-8 b']
end

